---
num_clients: 10
num_epochs: 10
batch_size: 64
clients_per_round: 10
learning_rate: 0.01  # eta_l - client learning rate for FedAvg
num_rounds: 10
partitioning: "iid"
dataset_name: "mnist"
dataset_seed: 42
alpha: 0.5
labels_per_client: 2
momentum: 0.9
weight_decay: 0.00001

initial_weights:
  enabled: true
  weights_dir: "saved_parameters"

client_fn:
  _target_: client_adaptive.gen_client_fn
  _recursive_: False
  num_epochs: ${num_epochs}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}

dataset:
  name: ${dataset_name}
  partitioning: ${partitioning}
  batch_size: ${batch_size}
  val_split: 0.2
  seed: ${dataset_seed}
  alpha: ${alpha}
  labels_per_client: ${labels_per_client}

model:
  _target_: models_adaptive.CNN
  input_dim: 400
  hidden_dims: [120, 84]
  num_classes: 10

strategy:
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 1.0
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:

server_device: cpu

client_resources:
  num_cpus: 4
  num_gpus: 0.0