---

num_clients: 100
num_epochs: 10
batch_size: 64
clients_per_round: 100
learning_rate: 0.01
num_rounds: 200
partitioning: "iid"
dataset_name: "mnist"
dataset_seed: 42
alpha: 0.5
labels_per_client: 2 # only used when partitioning is label_quantity
momentum: 0.9
weight_decay: 0.00001

# Initial weights configuration
initial_weights:
  enabled: true
  weights_dir: "saved_parameters"  # Directory containing the weight files
  # Weight files will be automatically selected based on dataset_name

client_fn:
  _target_: client_fednova.gen_client_fn
  _recursive_: False
  num_epochs: ${num_epochs}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}

dataset:
  # dataset config
  name: ${dataset_name}
  partitioning: ${partitioning}
  batch_size: ${batch_size} # batch_size = batch_size_ratio * total_local_data_size
  val_split: 0.0  # VALIDATION DISABLED: Set to 0.0 to use all training data for training
  seed: ${dataset_seed}
  alpha: ${alpha}
  labels_per_client: ${labels_per_client}

model:
  # model config
  _target_: models.CNN
  input_dim: 400
  hidden_dims: [120, 84]
  num_classes: 10

strategy:
  _target_: strategy.FedNovaStrategy
  # rest of strategy config
  fraction_fit: 1.0
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:
  # client config

server_device: cpu

client_resources:
  num_cpus: 4
  num_gpus: 0.0